/**
 * ## Gathering the resolutions
 * 
 * See [[collect_resolutions]] for the essential entry point.
 *
 * @packageDocumentation
*/

import { Resolution, JSONLDResolution, MinuteProcessing, GetDataCallback } from './types';
import { get_schema, flatten, DEBUG, LOG }                                 from './utils';

import * as showdown from 'showdown';
const converter = new showdown.Converter({
    omitExtraWLInCodeBlocks            : true,
    simplifiedAutoLink                 : true,
    excludeTrailingPunctuationFromURLs : true,
    literalMidWordUnderscores          : true,
    literalMidWordAsterisks            : true,
    strikethrough                      : true,
    ghMentions                         : true,
});
converter.setFlavor('github');


/**
 * Compare resolution objects; to be used in a “sort” method on the array of Resolutions.
 * 
 * Sorting takes a decreasing order by year, a decreasing order by meeting date within a year, and finally an increasing order by resolution number
 *  
 * @param  a - Left operand 
 * @param  b - Right operand
 * @returns - negative, zero, or positive, depending on the comparison result (see the Javascript “sort” method for details) 
 */
function sort_resolutions(a: Resolution, b: Resolution): number {
    if (a.year === b.year) {
        if (a.date === b.date) {
            return a.number - b.number;
        } else if (a.date < b.date) {
            return 1;
        } else {
            return -1;
        }
    } else {
        return b.year - a.year;
    }
}


/**
 * Get the resolution for a minute text (in markdown) of one call.
 * The function relies upon the JSON-LD metadata generated by scribejs. It:
 *
 * * extracts the URL, the date of the minutes, and the resolutions themselves from the preamble in JSON-LD;
 * * creates an array of [[Resolution]];
 *
 * @param minutes - the minutes for a call, in markdown
 * @returns - resolution data for one call
 * 
 */
function get_resolutions(minutes: string): Resolution[] {
    try {
        const lines: string[] = minutes.split('\n');
        const metadata: any     = get_schema(lines);
        if (metadata === null) {
            DEBUG(`The JSON-LD preamble is missing or could not be extracted`);
            return [];
        }
        DEBUG("schema: ", metadata);

        const url: string  = metadata.url;
        const date: string = metadata.dateCreated;
        if (date === undefined) {
            DEBUG(`For some reasons the date is missing`)
            return [];
        }
        const year: string = date.split('-')[0];
        const irc: string = metadata.irc;

        LOG(`Collecting resolutions for ${url}`)

        if (metadata.resolution && metadata.resolution.length > 0) {
            return (metadata.resolution as JSONLDResolution[]).map((res: JSONLDResolution): Resolution => {
                return {
                    year   : Number.parseInt(year),
                    date,
                    number : res.resolution_number,
                    text   : converter.makeHtml(res.resolution_text).replace('<p>','').replace('</p>',''), // the converter puts the text into a paragraph, hence the replace...
                    url    : `${url}#resolution${res.resolution_number}`,
                    call   : irc,
                }
            });
        } else {
            return [];
        }
    } catch (e) {
        DEBUG('Exception in resolution extraction: ',e)
        return [];
    }
}


/**
 * 
 * Collect all the resolutions. The function calls out, for each minute file, to the [[get_resolutions]] function,
 * and flattens all such resolutions into a single large resolution. The set of resolution is also sorted (using [[sort_resolutions]]).
 * 
 * @param file_names - List of the minute file names, i.e., the base name of the minute file in its repository
 * @param get_data - A function returning the markdown content of the minutes in a Promise. The function itself either uses the local file system read or a fetch to the repository, depending on whether this function is called for a local or a github repository.
 * @returns  - List of resolutions 
 * 
 * @async
 */
export async function collect_resolutions(file_names: string[], get_data: GetDataCallback): Promise<MinuteProcessing> {
    const minutes_promises: Promise<string>[] = file_names.map((file_name) => get_data(file_name));
    const minutes: string[]                   = await Promise.all(minutes_promises);
    const resolutions = minutes
        // extract all resolutions from the markdown text, returning an array of resolution objects
        .map(get_resolutions)
        // turn array of arrays into a single array
        .reduce(flatten,[])
        // sort the resolution.
        .sort(sort_resolutions);
    return {
        file_names : file_names,
        resolutions,
    }
}

